### ISSUE TITLE
[vehicle detail page] разменени линкове зад бутоните "редакция" и "качи снимка".

### ISSUE THREAD

**Issue by vtpetrov** [carspending/beta-issues#1]
**Issue:**
On the vehicle details, the links behind the buttons "edit vehicle details" and "upload image" are swapped.

- Link behind "**upload image**" -> http://v2-frontend.carspending.com/bg/vehicle/edit/1897
- Ling behind "**edit vehicle**" -> http://v2-frontend.carspending.com/bg/vehicle/upload-image?id=1897

**Screenshots:**
![vehichle_details-upload_image-wrong_link](https://cloud.githubusercontent.com/assets/1941241/24993307/73d2ade8-202e-11e7-8d5f-bbcc4a365118.png)
![vehichle_details-edit-wrong_link](https://cloud.githubusercontent.com/assets/1941241/24993345/a8e16cd6-202e-11e7-9c2a-2526dc3cf618.png)

**Vehicle details page** -> http://v2-frontend.carspending.com/bg/vehicle/1897-honda-accord-2-4i

**Comment by ddinchev** [comment]
Thank you, fixed!

**Comment by vtpetrov** [comment]
Йо, по празниците ли бачкаш? 😀
Като фикснеш нещо, директно ли го качваш на бетата?

Поздрави,
Веселин Петров

On 15 Apr 2017 15:34, "Dimitar Dinchev" <notifications@github.com> wrote:

Closed #1 <https://github.com/carspending/beta-issues/issues/1>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/carspending/beta-issues/issues/1#event-1044084762>, or mute
the thread
