### ISSUE TITLE
[garage][Firefox] the avatar image of the 1st vehicle is rendered in the middle instead top-left

### ISSUE THREAD

**Issue by vtpetrov** [carspending/beta-issues#3]
`browser`= **Firefox**
`number of vehicles in garage` = **3**
http://v2-frontend.carspending.com/bg/profile/vtpetrov

**Issue:**
The image of the 1st (top) listed vehicle in the garage is rendered in the middle of the vehicle card, as opposed to the top-left corner of the card when compared to the other vehicles.

The issue is present in both cases - with default image placeholder and with uploaded custom image.
See screenshots below.

**Screenshots:**
- Default image (placeholder):

![firefox-garage-3_vehicles-1st_image_center_position default](https://cloud.githubusercontent.com/assets/1941241/24996731/aad0a35a-203c-11e7-8e1e-6e789ebd9971.png)

- Custom image (with frame for better perception of the borders of the image):

![firefox-garage-3_vehicles-1st_image_center_position custom](https://cloud.githubusercontent.com/assets/1941241/24996734/ae3ff586-203c-11e7-8e3b-47ac6fc05736.png)

! `Note` !
**Chrome** is rendering the image correctly:

![chrome-fine](https://cloud.githubusercontent.com/assets/1941241/24996787/ece49d5a-203c-11e7-9fd6-44e27a694621.png)

**Comment by ddinchev** [comment]
Fixed.
