### ISSUE TITLE
[motorcycle] Cannot add new fueling for VehicleTypeID=2 (motorcycle/bike)

### ISSUE THREAD

**Issue by vtpetrov** [carspending/beta-issues#4]
**Issue:**
Upon an attempt to `add new fueling` for a **bike**(motorcycle) existing in my garage, I get error/exception page (see screenshot below).

Happens in both cases:
- when attempted from within the **garage** (http://v2-frontend.carspending.com/bg/profile/vtpetrov) using button inside vehicle card (link points to: http://v2-frontend.carspending.com/bg/fueling/add?VehicleID=1166&FuelTypeID=1)  : 
![garage-add_fuel-motorcycle-button](https://cloud.githubusercontent.com/assets/1941241/24998561/3378cc36-2043-11e7-8584-ec3ccb3b49d0.png)

- when attempted from within the **vehicle details page** (http://v2-frontend.carspending.com/bg/vehicle/1166-honda-vfr-800-rc46) using the button `add petrol` (link points to: http://v2-frontend.carspending.com/bg/fueling/add?VehicleID=1166&FuelTypeID=1 ) : 
![vehicle_details_page-add_petrol-button](https://cloud.githubusercontent.com/assets/1941241/24998567/384cf98a-2043-11e7-8194-aa6796cd443a.png)

**Result:**
Error page shown -> "PHP Notice – yii\base\ErrorException

Undefined index: Tyres"
![result-undefined_index_tyres](https://cloud.githubusercontent.com/assets/1941241/24998502/ff3c98e4-2042-11e7-91cb-7fbe78657540.png)

**Comment by vtpetrov** [comment]
The same exception is thrown If I try to `edit` a random existing record for the same vehicle (motorcycle).

**Comment by ddinchev** [comment]
Fixed.
