### ISSUE TITLE
[general] cannot delete fueling record

### ISSUE THREAD

**Issue by vtpetrov** [carspending/beta-issues#5]
Tried to delete 2 different records in 2 different vehicles in my profile and they both didn't succeed.
Result in `404 Not Found`

**Profile**:  http://v2-frontend.carspending.com/bg/profile/vtpetrov

- `Vehicle 1`:  http://v2-frontend.carspending.com/bg/vehicle/4027-renault-clio
-- vehicle 1, record to delete: 
![vehicle1 renault_clio _record1](https://cloud.githubusercontent.com/assets/1941241/25002192/d03172cc-2051-11e7-8be3-1bcda7e50c4f.png)
-- `target link` : http://v2-frontend.carspending.com/bg/fuelin/delete/120558

- `Vehicle 2`:  http://v2-frontend.carspending.com/bg/vehicle/1897-honda-accord-2-4i
-- vehicle 1, record to delete: 
![vehicle2 honda_accord _record1](https://cloud.githubusercontent.com/assets/1941241/25002272/25354794-2052-11e7-897d-da5aebaff591.png)
-- `target link` : http://v2-frontend.carspending.com/bg/fuelin/delete/120178

**Result:**
![result-404](https://cloud.githubusercontent.com/assets/1941241/25002307/5e6d3e40-2052-11e7-990b-26b4b1c6d4a6.png)

**Comment by ddinchev** [comment]
Fixed.
