### ISSUE TITLE
Yii DB issue while opening a car profile

### ISSUE THREAD

**Issue by scyberboy** [carspending/beta-issues#6]
[20170413_141300-yii_db_Exception.zip](https://github.com/carspending/beta-issues/files/919328/20170413_141300-yii_db_Exception.zip)

**Comment by vtpetrov** [comment]
I've experienced the same issue when I've tried to open `the vehicle profile page` in a **new browser tab**, `while` I had fueling record opened for `edit` in the _current browser tab_.

But I cannot reproduce it right now, so I neither have the exact steps nor I have narrowed down the root-cause.

**Comment by ddinchev** [comment]
I think this is due to the fact the beta server was on a very cheap VPS with 512MB of memory. Now I moved it to 1GB memory instance and it should be fine.
