### ISSUE TITLE
<br> tags visible in record details tooltip (bubble)

### ISSUE THREAD

**Issue by vtpetrov** [carspending/beta-issues#8]
Expense:
![expense-br_tags-tooltip](https://cloud.githubusercontent.com/assets/1941241/25003655/3a4ece50-2059-11e7-9757-11081e067b85.png)
`expense record ID:` **46577**
`link`: http://v2-frontend.carspending.com/bg/expense/edit/46577

Fueling:
![fueling-br_tags-tooltip](https://cloud.githubusercontent.com/assets/1941241/25003699/68c1a4ec-2059-11e7-9a30-7fdc55a37886.png)
`fueling record link:` http://v2-frontend.carspending.com/bg/fueling/edit/120558

The Issue occurs when inside the free text field of the record, the user used "Enter" to place new lines (write on a new line).

**Comment by ddinchev** [comment]
Fixed.
